import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { TanstackProvider } from "@/components/providers/tanstack";
import Head from "next/head";
import { GoeyToaster } from "@/components/ui/goey-toaster";

const fontSans = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "PPI Bartin App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-ppi.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <script
          async
          crossOrigin="anonymous"
          src="https://tweakcn.com/live-preview.min.js"
        />
      </Head>
      <body className={`${fontSans.variable} antialiased`}>
        <main>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TanstackProvider>
              <GoeyToaster position="top-center" />
              {children}
            </TanstackProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
