import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { TanstackProvider } from "@/components/providers/tanstack";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "PPI Bartin App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-ppi.png",
    apple: "/logo-ppi.png",
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "PPI Bartin",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <meta name="theme-color" content="#2563eb" />
      <body className="antialiased min-h-screen w-full relative">
        <main>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TanstackProvider>
              <Toaster position="top-center" />
              <SpeedInsights />
              {children}
            </TanstackProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
