import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PPI Bartin | Acara-acara",
  description: "Generated by create next app",
};

const HomeLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="relative mb-24 max-w-xl md:max-w-3xl xl:max-w-6xl mx-auto">
      {children}
    </div>
  );
};

export default HomeLayout;
