import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PPI Bartin | Acara-acara",
  description: "Generated by create next app",
};

const HomeLayout = ({ children }: { children: React.ReactNode }) => {
  return <div className="relative mb-24">{children}</div>;
};

export default HomeLayout;
