import NavMainEvent from "@/components/event/nav-event";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PPI Bartin | Acara-acara",
  description: "Generated by create next app",
};

export const HomeLayoutComponent = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <div>
      <NavMainEvent />
      {children}
    </div>
  );
};
