import { auth } from "@/lib/auth";
import { checkNoSiswa } from "@/server/data/users";
import { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "PPI Bartin | complite profile",
  description: "Generated by create next app",
};

const CompleteProfileLayout = async ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  if (!session) redirect("/login");

  const student = await checkNoSiswa();

  if (!student?.nomorSiswa) {
    redirect("/register-profile");
  }

  if (student.username) {
    redirect("/home");
  }

  return <>{children}</>;
};

export default CompleteProfileLayout;
