import { Metadata } from "next";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { HomeLayoutComponent } from "@/components/layout/home-layout";
import { Footer } from "@/components/sections/footer";
import { Navbar } from "@/components/sections/navbar";

export const metadata: Metadata = {
  title: "PPI Bartin | Login",
  description: "Generated by create next app",
};

const PublicLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await auth.api.getSession({ headers: await headers() });

  if (session) {
    return <HomeLayoutComponent>{children}</HomeLayoutComponent>;
  }

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />
      <main className="flex-1 pt-16">{children}</main>
      <Footer />
    </div>
  );
};

export default PublicLayout;
